# Generated by Django 3.2.5 on 2021-08-22 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StrengthDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('strength_date', models.DateTimeField(verbose_name='strength exercise date')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ediary.exercisetype')),
            ],
        ),
        migrations.CreateModel(
            name='CardioDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardio_date', models.DateTimeField(verbose_name='cardio exercise date')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ediary.exerciselocation')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ediary.exercisetype')),
            ],
        ),
    ]
